### ISSUE TITLE
error

### ISSUE THREAD

**Issue by fdciabdul** [Yooootsuba/TwitterVideoDownloader#1]
`Fatal error: Uncaught Requests_Exception: Only HTTP(S) requests are handled. in /data/data/com.termux/files/home/TwitterVideoDownloader/vendor/rmccue/requests/library/Requests.php:564`

**Comment by Yooootsuba** [comment]
I did not encounter this error while developing .

Could you please provide a Twitter video url for testing ?

**Comment by fdciabdul** [comment]
> I did not encounter this error while developing .
> 
> Could you please provide a Twitter video url for testing ?

i use this https://twitter.com/sucker4michael/status/1267854913117343744?s=20


[Screenshot_2020_0602_232705](https://user-images.githubusercontent.com/31664438/83544777-a1337380-a528-11ea-9411-45af226d6926.png)

**Comment by Yooootsuba** [comment]
The problem is that you have more string "?=20"

Just right click video and press "Copy Video Address"

Try this url : https://twitter.com/sucker4michael/status/1267854913117343744
